# Generated by Django 3.0.6 on 2020-06-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banksubbranch',
            fields=[
                ('bankname', models.CharField(db_column='bankName', max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('property', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'db_table': 'banksubbranch',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('accountid', models.CharField(db_column='accountID', max_length=36, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('opentime', models.DateTimeField(blank=True, db_column='openTime', null=True)),
                ('visittime', models.DateTimeField(blank=True, db_column='visitTime', null=True)),
                ('overdraft', models.DecimalField(decimal_places=2, max_digits=16)),
                ('bankname', models.ForeignKey(db_column='bankName', on_delete=django.db.models.deletion.PROTECT, to='login.Banksubbranch')),
            ],
            options={
                'db_table': 'cheque',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentnum', models.CharField(db_column='departmentNum', max_length=18, primary_key=True, serialize=False)),
                ('manager', models.CharField(blank=True, max_length=18, null=True)),
                ('departmentname', models.CharField(blank=True, db_column='departmentName', max_length=18, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('bankname', models.ForeignKey(blank=True, db_column='bankName', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Banksubbranch')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanid', models.CharField(db_column='loanID', max_length=18, primary_key=True, serialize=False)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=16)),
                ('times', models.IntegerField(blank=True, null=True)),
                ('paysum', models.DecimalField(db_column='paySum', decimal_places=2, max_digits=16)),
                ('state', models.CharField(blank=True, max_length=1, null=True)),
                ('bankname', models.ForeignKey(db_column='bankName', on_delete=django.db.models.deletion.PROTECT, to='login.Banksubbranch')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('accountid', models.CharField(db_column='accountID', max_length=36, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('opentime', models.DateTimeField(blank=True, db_column='openTime', null=True)),
                ('visittime', models.DateTimeField(blank=True, db_column='visitTime', null=True)),
                ('rate', models.FloatField()),
                ('currency', models.CharField(max_length=24)),
                ('bankname', models.ForeignKey(db_column='bankName', on_delete=django.db.models.deletion.PROTECT, to='login.Banksubbranch')),
            ],
            options={
                'db_table': 'save',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.CharField(db_column='staffID', max_length=18, primary_key=True, serialize=False)),
                ('startdate', models.DateField(db_column='startDate')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('staffname', models.CharField(db_column='staffName', max_length=18)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('departmentnum', models.ForeignKey(blank=True, db_column='departmentNum', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Department')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(db_column='customerID', max_length=18, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('customername', models.CharField(db_column='customerName', max_length=18)),
                ('createtime', models.DateTimeField(db_column='createTime')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('linkmanemail', models.CharField(db_column='linkmanEmail', max_length=64)),
                ('linkmanname', models.CharField(db_column='linkmanName', max_length=18)),
                ('linkmanphone', models.CharField(blank=True, db_column='linkmanPhone', max_length=11, null=True)),
                ('linkmanrelationship', models.CharField(blank=True, db_column='linkmanRelationship', max_length=64, null=True)),
                ('staffid', models.ForeignKey(blank=True, db_column='staffID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.Staff')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Saveinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businesstype', models.CharField(db_column='businessType', max_length=1)),
                ('visittime', models.DateTimeField(db_column='visitTime')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('accountid', models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, to='login.Save')),
            ],
            options={
                'db_table': 'saveinfo',
                'unique_together': {('accountid', 'visittime')},
            },
        ),
        migrations.CreateModel(
            name='Savecustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, to='login.Save')),
                ('customerid', models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.PROTECT, to='login.Customer')),
            ],
            options={
                'db_table': 'savecustomer',
                'unique_together': {('customerid', 'accountid')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytime', models.DateTimeField(db_column='payTime')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=16)),
                ('loanid', models.ForeignKey(db_column='loanID', on_delete=django.db.models.deletion.CASCADE, to='login.Loan')),
            ],
            options={
                'db_table': 'payment',
                'unique_together': {('loanid', 'paytime')},
            },
        ),
        migrations.CreateModel(
            name='Customerloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.PROTECT, to='login.Customer')),
                ('loanid', models.ForeignKey(db_column='loanID', on_delete=django.db.models.deletion.CASCADE, to='login.Loan')),
            ],
            options={
                'db_table': 'customerloan',
                'unique_together': {('loanid', 'customerid')},
            },
        ),
        migrations.CreateModel(
            name='Chequeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businesstype', models.CharField(db_column='businessType', max_length=1)),
                ('visittime', models.DateTimeField(db_column='visitTime')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('accountid', models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, to='login.Cheque')),
            ],
            options={
                'db_table': 'chequeinfo',
                'unique_together': {('accountid', 'visittime')},
            },
        ),
        migrations.CreateModel(
            name='Chequecustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, to='login.Cheque')),
                ('customerid', models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.PROTECT, to='login.Customer')),
            ],
            options={
                'db_table': 'chequecustomer',
                'unique_together': {('customerid', 'accountid')},
            },
        ),
        migrations.CreateModel(
            name='Bankcustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounttype', models.CharField(db_column='accountType', max_length=1)),
                ('bankname', models.ForeignKey(db_column='bankName', on_delete=django.db.models.deletion.PROTECT, to='login.Banksubbranch')),
                ('customerid', models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.CASCADE, to='login.Customer')),
            ],
            options={
                'db_table': 'bankcustomer',
                'unique_together': {('bankname', 'customerid', 'accounttype')},
            },
        ),
    ]
